name: mcvine
channels:
- neutrons
- mantid
- mcvine
- conda-forge
- defaults
dependencies:
- ase=3.15.0=py27_1
- attrs=17.4.0=py_0
- awscli=1.14.32=py27_0
- backports.shutil_get_terminal_size=1.0.0=py27_0
- backports_abc=0.4=py27_0
- bleach=2.0.0=py27_0
- boto3=1.5.22=py_0
- botocore=1.8.36=py_0
- ca-certificates=2016.8.2=3
- certifi=2016.8.2=py27_0
- click=6.7=py27_0
- cloudpickle=0.2.2=py27_2
- cmake=3.6.1=0
- colorama=0.3.7=py27_0
- configparser=3.5.0b2=py27_0
- curl=7.49.1=1
- cycler=0.10.0=py27_0
- dask=0.14.0=py27_0
- dask-core=0.15.4=py_0
- dbus=1.10.22=0
- decorator=4.0.10=py27_0
- distributed=1.16.0=py27_0
- docutils=0.12=py27_0
- entrypoints=0.2.2=py27_0
- expat=2.1.0=2
- flask=0.12.2=py27_0
- funcsigs=1.0.2=py_2
- functools32=3.2.3.2=py27_1
- futures=3.0.5=py27_0
- gettext=0.19.7=1
- gmp=6.1.2=0
- gsl=2.1=2
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=1
- h5py=2.7.1=py27_1
- hdf4=4.2.12=0
- hdf5=1.8.18=1
- heapdict=1.0.0=py27_0
- html5lib=0.999999999=py27_0
- imageio=2.2.0=py27_0
- ipykernel=4.3.1=py27_1
- ipython=5.0.0=py27_0
- ipywidgets=5.2.2=py27_0
- itsdangerous=0.24=py_2
- jinja2=2.8=py27_1
- jmespath=0.9.0=py27_0
- jpeg=9b=0
- jsoncpp=0.10.6=1
- jsonschema=2.5.1=py27_0
- jupyter_client=4.3.0=py27_0
- jupyter_console=5.0.0=py27_0
- jupyter_core=4.1.0=py27_0
- libarchive=3.2.1=2
- libffi=3.2.1=2
- libiconv=1.14=3
- libpng=1.6.28=1
- libsodium=1.0.10=0
- libtiff=4.0.6=6
- libxcb=1.12=1
- lmfit=0.9.7=py27_0
- locket=0.2.0=py27_1
- markupsafe=0.23=py27_0
- mistune=0.7.4=py27_0
- msgpack-python=0.4.8=py27_0
- muparser=2.2.5=1
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py27_0
- ncurses=5.9=8
- networkx=1.11=py27_0
- notebook=4.2.2=py27_0
- olefile=0.44=py27_0
- openblas=0.2.20=2
- openssl=1.0.2h=2
- pandas=0.20.3=py27_1
- pandoc=1.19.2=0
- pandocfilters=1.4.1=py27_0
- partd=0.3.7=py27_0
- pathlib2=2.1.0=py27_0
- pcre=8.39=0
- pexpect=4.2.0=py27_1
- phonopy=1.11.14.1=py27_0
- pickleshare=0.7.3=py27_0
- pillow=3.2.0=py27_1
- pip=8.1.2=py27_0
- pixman=0.34.0=0
- pluggy=0.6.0=py_0
- prompt_toolkit=1.0.4=py27_0
- psutil=4.3.0=py27_0
- ptyprocess=0.5.1=py27_0
- py=1.5.2=py_0
- pyasn1=0.4.2=py_0
- pycairo=1.13.3=py27_0
- pygments=2.1.3=py27_0
- pyparsing=2.1.7=py27_0
- pyqt=5.6.0=py27_4
- pytest=3.4.0=py27_0
- python-dateutil=2.5.3=py27_0
- pytz=2016.6.1=py27_0
- pywavelets=0.5.2=np113py27_0
- pyyaml=3.11=py27_0
- pyzmq=15.3.0=py27_0
- qtconsole=4.2.1=py27_0
- readline=6.2=0
- requests=2.13.0=py27_0
- rsa=3.4.2=py27_0
- s3fs=0.0.9=py27_0
- s3transfer=0.1.12=py27_0
- scikit-image=0.13.0=py27_2
- setuptools=25.1.4=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sortedcontainers=1.5.3=py27_0
- sqlite=3.13.0=1
- ssl_match_hostname=3.5.0.1=py27_0
- subprocess32=3.2.7=py27_0
- tbb=2018_20170919=0
- terminado=0.6=py27_0
- testpath=0.3.1=py27_0
- toolz=0.8.2=py27_0
- tornado=4.4.1=py27_1
- traitlets=4.2.2=py27_0
- wcwidth=0.1.7=py27_0
- webencodings=0.5=py27_0
- werkzeug=0.12.2=py_1
- wheel=0.29.0=py27_0
- widgetsnbextension=1.2.6=py27_3
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- xz=5.2.2=0
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zict=0.1.1=py27_0
- zlib=1.2.8=3
- bokeh=0.12.4=py27_0
- boost=1.61.0=py27_0
- bzip2=1.0.6=3
- cairo=1.14.8=0
- dateutil=2.4.1=py27_0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- glib=2.50.2=1
- harfbuzz=0.9.39=1
- icu=54.1=0
- ipython_genutils=0.1.0=py27_0
- jupyter=1.0.0=py27_3
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libxml2=2.9.4=0
- matplotlib=2.0.2=np113py27_0
- mkl=2017.0.3=0
- mpi4py=2.0.0=py27_1
- mpich2=1.4.1p1=0
- numpy=1.13.1=py27_0
- pango=1.40.3=1
- python=2.7.12=1
- qt=5.6.2=5
- scipy=0.19.1=np113py27_0
- tblib=1.3.0=py27_0
- tk=8.5.18=0
- mantid-framework=3.10=np113py27_gsl2
- nexus=4.3.1=py27_0
- poco=1.7.3=py27_0
- danse.ins=0.1=py27_0
- danse.ins.bpext=0.1=py27_0
- danse.ins.dsm=0.1=0
- danse.ins.matter=0.9=0
- danse.ins.numpyext=0.1=py27_0
- drchops=2.0alpha=0
- histogram=0.3.1=py27_0
- journal=0.8=py27_0
- mantid2mcvine=0.1.0a3=py27_0
- mcvine=1.3.1=0
- mcvine-core=1.3.1=np113py27_0
- mcvine-resources=1.0.1=0
- mcvine.instruments=0.1.0a3=py27_0
- mcvine.phonon=0.1.0a4=py27_0
- mcvine.workflow=0.1.0a4=py27_0
- pyre=0.8=py27_0
- pip:
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - periodictable==1.4.1
  - prompt-toolkit==1.0.4
  - pycifrw==4.3
