channels:
- mcvine
- mantid
- conda-forge
dependencies:
- mcvine=1.3.1
- mantid-framework=3.10
- notebook=5.4
- ipykernel=4.6
- ipywidgets=7.0
- widgetsnbextension=3.0
- matplotlib=2.0.2
- python=2.7
